# Generated by Django 4.1.1 on 2022-09-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Modellar',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=255)),
                ('ram', models.CharField(blank=True, choices=[('2', '2'), ('3', '3'), ('4', '4'), ('8', '8'), ('12', '12')], max_length=255, null=True)),
                ('rom', models.CharField(blank=True, choices=[('32', '32'), ('64', '64'), ('128', '128'), ('256', '256'), ('512', '512')], max_length=255, null=True)),
                ('color', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apelsin.category')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apelsin.model')),
            ],
            options={
                'verbose_name': 'Telefon va gadjetlar',
                'verbose_name_plural': 'Telefon va gadjetlar',
            },
        ),
    ]
