# Generated by Django 4.1.1 on 2022-09-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('price', models.CharField(max_length=255)),
                ('ram', models.CharField(blank=True, choices=[('4', '4'), ('8', '8'), ('12', '12')], max_length=255, null=True)),
                ('rom', models.CharField(blank=True, choices=[('32', '32'), ('64', '64'), ('128', '128'), ('256', '256')], max_length=255, null=True)),
                ('color', models.CharField(max_length=255)),
                ('describtions', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apelsin.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
