# Generated by Django 4.1.1 on 2022-09-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apelsin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Telefon va gadjetlar', 'verbose_name_plural': 'Telefon va gadjetlar'},
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='describtions',
            new_name='descriptions',
        ),
    ]
