# Generated by Django 4.1.1 on 2022-09-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apelsin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='sssssss', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=255),
        ),
    ]
